version: '3'

networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    user: '501'
    container_name: loki
    volumes:
      - ./loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /Users/souvikojha/Desktop/authlayer- assigment/assignment-devops-1/logs:/var/log
      # - /var/log:/var/log
      - ./promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    user : '501'
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loki