server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: local
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
  pipeline_stages:
    - json:
        expressions:
          timestamp: timestamp   # Extract the 'timestamp' field
          level: level           # Extract the 'level' field
          service: service       # Extract the 'service' field
          message: message       # Extract the 'message' field
    - labels:
        service: ""